//
// Generated by ChatGPT 3.5 (OpenAI API)
//

class MockHogeProtocol: HogeProtocol {
    var title: String = ""
    var index: Int = 0
    var somethingValue: String? = nil
    
    func something(with value: String) -> Something {
        self.somethingValue = value
        return Something()
    }
}

class Something {
    //Mock implementation
}