//
//  File.swift
//  
//
//  Created by 日野森 寛也（Hiroya Hinomori） on 2023/04/11.
//

import Foundation

enum GenerateFileHeader {
    static var header: String {
        """
        //
        // Generated by ChatGPT 3.5 (OpenAI API)
        //
        
        """
    }
}
