//
// Generated by ChatGPT 3.5 (OpenAI API)
//

import XCTest
@testable import Core

class MapperGeneratorTests: XCTestCase {
    
    let sourceFilePath = URL(fileURLWithPath: "source.swift")
    let destinationFilePath = URL(fileURLWithPath: "destination.swift")
    let outputDirectoryPath = URL(fileURLWithPath: "output")
    
    // Test initialization sets properties correctly
    func testInit() {
        let mapperGen = MapperGenerator(sourceFilePath: sourceFilePath, 
                                        destinationFilePath: destinationFilePath, 
                                        outputDirectoryPath: outputDirectoryPath)
        
        XCTAssertEqual(mapperGen.sourceFilePath, sourceFilePath)
        XCTAssertEqual(mapperGen.destinationFilePath, destinationFilePath)
        XCTAssertEqual(mapperGen.outputDirectoryPath, outputDirectoryPath)
    }
    
    // Test expected output file path is returned
    func testCreateOutputPath() {
        let mapperGen = MapperGenerator(sourceFilePath: sourceFilePath, 
                                        destinationFilePath: destinationFilePath, 
                                        outputDirectoryPath: outputDirectoryPath)
        let expectedPath = outputDirectoryPath.appendingPathComponent("destinationMapper.swift")
        XCTAssertEqual(mapperGen.createOutputPath(), expectedPath)
    }
    
    // Test file name is correctly created
    func testCreateFileName() {
        let mapperGen = MapperGenerator(sourceFilePath: sourceFilePath, 
                                        destinationFilePath: destinationFilePath, 
                                        outputDirectoryPath: outputDirectoryPath)
        XCTAssertEqual(mapperGen.createFileName(), "destinationMapper.swift")
    }
    
    // Test order string is generated correctly
    func testCreateOrder() {
        let mapperGen = MapperGenerator(sourceFilePath: sourceFilePath, 
                                        destinationFilePath: destinationFilePath, 
                                        outputDirectoryPath: outputDirectoryPath)
        let expectedOrder = "Generate destinationMapper struct for them with Swift without comment.\n\n\n\n"
        XCTAssertEqual(mapperGen.createOrder(), expectedOrder)
    }

}
