//
// Generated by ChatGPT 3.5 (OpenAI API)
//

import XCTest
@testable import Core

class UnitTestGeneratorTests: XCTestCase {

    func test_createOrder() {
        let content = "some content"
        let expectedResult = "Generate unit test for this codes with Swift without comment.\n\nsome content"
        XCTAssertEqual(UnitTestGenerator.createOrder(content), expectedResult)
    }

    func test_createOutputFileName() {
        let inputFileName = "MyModule.swift"
        let expectedOutputFileName = "MyModuleTests+ChatGPT.swift"
        XCTAssertEqual(UnitTestGenerator.createOutputFileName(inputFileName), expectedOutputFileName)
    }
}
