//
// Generated by ChatGPT 3.5 (OpenAI API)
//

import XCTest
@testable import Core

class UnitTestGeneratorTests: XCTestCase {
    
    var inputFilePath: URL!
    var outputDirectoryPath: URL!
    var generator: UnitTestGenerator!
    
    override func setUp() {
        super.setUp()
        inputFilePath = URL(fileURLWithPath: "/path/to/input/file.swift")
        outputDirectoryPath = URL(fileURLWithPath: "/path/to/output/directory/")
        generator = UnitTestGenerator(inputFilePath: inputFilePath, outputDirectoryPath: outputDirectoryPath)
    }
    
    override func tearDown() {
        inputFilePath = nil
        outputDirectoryPath = nil
        generator = nil
        super.tearDown()
    }
    
    func testCreateOrder() {
        let order = generator.createOrder()
        XCTAssertGreaterThan(order.count, 0)
    }
    
    func testCreateOutputPath() {
        let outputPath = generator.createOutputPath()
        XCTAssertEqual(outputPath.pathExtension, "swift")
    }
    
    func testCreateFileName() {
        let fileName = generator.createFileName()
        XCTAssertEqual(fileName, "fileTests+ChatGPT.swift")
    }
}
