//
// Generated by ChatGPT 3.5 (OpenAI API)
//
import XCTest
@testable import Core

class UnitTestGeneratorTests: XCTestCase {
    
    func test_createOrder() {
        let expectedOrder = "Generate unit test for this codes with Swift without comment.\n\nCode sample"
        let generatedOrder = UnitTestGenerator.createOrder("Code sample")
        XCTAssertEqual(expectedOrder, generatedOrder)
    }
    
    func test_createOutputFileName() {
        let expectedOutputFileName = "MyModuleTests+ChatGPT.swift"
        let inputFileName = "MyModule.swift"
        let generatedOutputFileName = UnitTestGenerator.createOutputFileName(inputFileName)
        XCTAssertEqual(expectedOutputFileName, generatedOutputFileName)
    }
}
